### ISSUE TITLE
Crash when orientation changes

### ISSUE THREAD

**Issue by zorius** [harism/android-pagecurl#53]
Sometimes when orientation changes I'm having a crash. Don't know why it is happening because only occurs sometimes when doing fast movements of rotation.

I can't to find wax to fix it now. How can I fix it? 

Here is the crash log:

01-25 12:16:30.429: W/SurfaceView(2816): mSurface is not valid! creating=true formatChanged=true sizeChanged=true visible=true visibleChanged=true surfaceChanged=false realSizeChanged=true redrawNeeded=true left=false top=false
01-25 12:16:30.429: W/SurfaceView(2816): java.lang.RuntimeException
01-25 12:16:30.429: W/SurfaceView(2816):    at android.view.SurfaceView.updateWindow(SurfaceView.java:532)
01-25 12:16:30.429: W/SurfaceView(2816):    at android.view.SurfaceView.access$000(SurfaceView.java:81)
01-25 12:16:30.429: W/SurfaceView(2816):    at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:169)
01-25 12:16:30.429: W/SurfaceView(2816):    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:590)
01-25 12:16:30.429: W/SurfaceView(2816):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1710)
01-25 12:16:30.429: W/SurfaceView(2816):    at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2539)
01-25 12:16:30.429: W/SurfaceView(2816):    at android.os.Handler.dispatchMessage(Handler.java:99)
01-25 12:16:30.429: W/SurfaceView(2816):    at android.os.Looper.loop(Looper.java:137)
01-25 12:16:30.429: W/SurfaceView(2816):    at android.app.ActivityThread.main(ActivityThread.java:4514)
01-25 12:16:30.429: W/SurfaceView(2816):    at java.lang.reflect.Method.invokeNative(Native Method)
01-25 12:16:30.429: W/SurfaceView(2816):    at java.lang.reflect.Method.invoke(Method.java:511)
01-25 12:16:30.429: W/SurfaceView(2816):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
01-25 12:16:30.429: W/SurfaceView(2816):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
01-25 12:16:30.429: W/SurfaceView(2816):    at dalvik.system.NativeStart.main(Native Method)

01-25 12:16:30.445: E/GLSurfaceView(2816): eglCreateWindowSurface
01-25 12:16:30.445: E/GLSurfaceView(2816): java.lang.IllegalArgumentException: Make sure the SurfaceView or associated SurfaceHolder has a valid Surface
01-25 12:16:30.445: E/GLSurfaceView(2816):  at com.google.android.gles_jni.EGLImpl._eglCreateWindowSurface(Native Method)
01-25 12:16:30.445: E/GLSurfaceView(2816):  at com.google.android.gles_jni.EGLImpl.eglCreateWindowSurface(EGLImpl.java:90)
01-25 12:16:30.445: E/GLSurfaceView(2816):  at android.opengl.GLSurfaceView$DefaultWindowSurfaceFactory.createWindowSurface(GLSurfaceView.java:798)
01-25 12:16:30.445: E/GLSurfaceView(2816):  at android.opengl.GLSurfaceView$EglHelper.createSurface(GLSurfaceView.java:1065)
01-25 12:16:30.445: E/GLSurfaceView(2816):  at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1433)
01-25 12:16:30.445: E/GLSurfaceView(2816):  at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1216)

**Comment by harism** [comment]
Is this stack trace from a phone or emulator? Also, are you using master or OpenGL ES 2.0 branch? At first glance it looks like there isn't necessary much I can do about this crash as it seems to happen somewhere within underlying OpenGL implementation.

**Comment by zorius** [comment]
I'm using a Samsung tablet and OpenGL ES 2.0 branch. I don't really know what is the cause of this. Seems like the  CurlView is being used before SurfaceHolder is valid.

**Comment by harism** [comment]
Hmm.. I did some Googling and all I found that could be related to crash you're facing was this;
http://stackoverflow.com/questions/12855103/eglcreatewindowsurface-fails-with-java-lang-illegalargumentexception
