### ISSUE TITLE
App crashes on API level 11+ 

### ISSUE THREAD

**Issue by geo47** [harism/android-pagecurl#83]
Hello Harism!
I tried curl page example, it works for me on Android api level 10 and 11 but crashes on above versions with following exception: 

--------- beginning of crash
01-07 17:31:08.464    1264-1304/? E/AndroidRuntime﹕ FATAL EXCEPTION: GLThread 139
    Process: fi.harism.curl, PID: 1264
    java.lang.IllegalArgumentException: No config chosen
            at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:869)
            at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1023)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1400)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)

can you please help me to get it fix...
Thanks in advance...

**Comment by geo47** [comment]
I got my Problem solved... 
It was actually the problem of OpenGL support in emulator

I set the configuration setting in the CurlView class init method as:
super.setEGLConfigChooser(8 , 8, 8, 8, 16, 0);

and everything works fine :)
